
DESCRIPTIONS = {
        'p': "The /p/ sound is unvoiced; close your lips and release a small burst of air.",
        'b': "The /b/ sound is voiced; close your lips and release while vibrating your vocal cords.",
        't': "The /t/ sound is unvoiced; place your tongue behind your teeth and release a quick burst of air.",
        'd': "The /d/ sound is voiced; place your tongue behind your teeth and release while vibrating your vocal cords.",
        'k': "The /k/ sound is unvoiced; raise the back of your tongue to the soft palate and release air.",
        'g': "The /g/ sound is voiced; raise the back of your tongue to the soft palate and vibrate your vocal cords.",
        'f': "The /f/ sound is unvoiced; touch your top teeth to your bottom lip and blow air.",
        'v': "The /v/ sound is voiced; touch your top teeth to your bottom lip and vibrate your vocal cords.",
        'θ': "The /θ/ sound is unvoiced; place your tongue between your teeth without vibrating your vocal cords.",
        'ð': "The /ð/ sound is voiced; place your tongue between your teeth and vibrate your vocal cords.",
        's': "The /s/ sound is unvoiced; push air over the tongue and through the teeth.",
        'z': "The /z/ sound is voiced; push air over the tongue and through the teeth while vibrating your vocal cords.",
        'ʃ': "The /ʃ/ sound is unvoiced; curl your tongue slightly and blow air, like in 'ship'.",
        'ʒ': "The /ʒ/ sound is voiced; curl your tongue slightly and vibrate your vocal cords, like in 'measure'.",
        'ʧ': "The /ʧ/ sound is unvoiced; stop then release air with a 'sh' sound, like in 'church'.",
        'ʤ': "The /ʤ/ sound is voiced; stop then release air with a 'zh' sound, like in 'judge'.",
        'm': "The /m/ sound is voiced; close your lips and let air flow through your nose.",
        'n': "The /n/ sound is voiced; touch your tongue behind your teeth and let air through your nose.",
        'ŋ': "The /ŋ/ sound is voiced; raise the back of your tongue and let air through your nose, like in 'sing'.",
        'h': "The /h/ sound is unvoiced; exhale softly through your open mouth.",
        'l': "The /l/ sound is voiced; place your tongue behind your upper teeth and let air pass around the sides.",
        'r': "The /r/ sound is voiced; curl your tongue slightly without touching the roof of your mouth.",
        'w': "The /w/ sound is voiced; round your lips and glide into the next sound.",
        'j': "The /j/ sound is voiced; raise the middle of your tongue toward the roof of your mouth.",
        'i': "The /i/ vowel is high and front; spread your lips, like in 'see'.",
        'ɪ': "The /ɪ/ vowel is high and near-front; relaxed tongue, like in 'bit'.",
        'e': "The /e/ vowel is mid-high and front; like the first part of 'day'.",
        'ɛ': "The /ɛ/ vowel is mid-low and front; like in 'bed'.",
        'æ': "The /æ/ vowel is low and front; mouth open wide, like in 'cat'.",
        'ʌ': "The /ʌ/ vowel is mid-central; tongue low-mid back, like in 'cup'.",
        'ə': "The /ə/ vowel is mid-central; tongue in neutral position, like the 'a' in 'sofa'.",
        'ɑ': "The /ɑ/ vowel is low and back; mouth open, like in 'father'.",
        'ɔ': "The /ɔ/ vowel is mid-low and back; lips rounded, like in 'law'.",
        'ʊ': "The /ʊ/ vowel is high and back; lips rounded, like in 'book'.",
        'u': "The /u/ vowel is high and back; lips rounded tightly, like in 'food'.",
        'aɪ': "The /aɪ/ sound starts low front and glides to high front, like in 'my'.",
        'aʊ': "The /aʊ/ sound starts low front and glides to high back, like in 'now'.",
        'ɔɪ': "The /ɔɪ/ sound starts mid-back and glides to high front, like in 'boy'.",
        'eɪ': "The /eɪ/ sound starts mid-front and glides upward, like in 'say'.",
        'oʊ': "The /oʊ/ sound starts mid-back and glides upward, like in 'go'."
        }

AFFIRMATIONS = [
    "Great job!",
    "Nice work!",
    "You're getting it!",
    "Perfect pronunciation!",
    "Keep it up!",
    "Sounds great!",
    "You're doing awesome!",
    "Spot on!",
    "Nailed it!",
    "Excellent!"
]